"""send_at column added

Revision ID: 4094faf5cef6
Revises: a1ae75f8ced1
Create Date: 2025-07-11 15:38:34.800872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4094faf5cef6'
down_revision: Union[str, Sequence[str], None] = 'a1ae75f8ced1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('send_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'send_at')
    # ### end Alembic commands ###
