"""email column added

Revision ID: a1ae75f8ced1
Revises: 1489357b61bc
Create Date: 2025-07-09 17:38:48.216988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1ae75f8ced1'
down_revision: Union[str, Sequence[str], None] = '1489357b61bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guest', sa.Column('email', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'guest', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'guest', type_='unique')
    op.drop_column('guest', 'email')
    # ### end Alembic commands ###
